
version: '3.9'
services:
  vault:
    image: vault:latest
    container_name: vault
    restart: on-failure:10
    networks:
      - back
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
    cap_add:
    -  IPC_LOCK
    command: server -dev
    
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - back


networks:
  back: {}